# Generated by Django 4.0.4 on 2022-04-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_productattribut_productattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories'},
        ),
    ]
