# Generated by Django 4.0.4 on 2022-04-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '7. Banner'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '6. ProductAttribute'},
        ),
    ]
