# Generated by Django 4.0.4 on 2022-04-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
