# Generated by Django 4.0.4 on 2022-04-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
